//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaUrgencia_v2._0.DataL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosUrgencia
    {
        public int id_datosUrgencia { get; set; }
        public Nullable<int> N_hoja { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public string especialidad { get; set; }
        public string Motivo_consulta { get; set; }
        public Nullable<int> id_modo_ingreso { get; set; }
        public Nullable<int> id_val_ini { get; set; }
    
        public virtual Ingresos Ingresos { get; set; }
        public virtual Valoracion_inicial Valoracion_inicial { get; set; }
    }
}
