//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaUrgencia_v2._0.DataL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Imagenes()
        {
            this.Valoracion_inicial = new HashSet<Valoracion_inicial>();
        }
    
        public int id_imagen { get; set; }
        public Nullable<int> id_solicitud_fk { get; set; }
        public Nullable<bool> cabeza { get; set; }
        public Nullable<bool> Ext_sup_Izq { get; set; }
        public Nullable<bool> Ext_sup_Der { get; set; }
        public Nullable<bool> tronco { get; set; }
        public Nullable<bool> Ext_inf_Izq { get; set; }
        public Nullable<bool> Ext_inf_Der { get; set; }
    
        public virtual Solicitud Solicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valoracion_inicial> Valoracion_inicial { get; set; }
    }
}
