//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaUrgencia_v2._0.DataL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perdida_liquidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Perdida_liquidos()
        {
            this.Valoracion_inicial = new HashSet<Valoracion_inicial>();
        }
    
        public int id_PL { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public string diuresis { get; set; }
        public string deposicion { get; set; }
        public string vomito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valoracion_inicial> Valoracion_inicial { get; set; }
    }
}
