//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaUrgencia_v2._0.DataL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescripcion_Emergencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prescripcion_Emergencia()
        {
            this.Valoracion_inicial = new HashSet<Valoracion_inicial>();
        }
    
        public int id_tratamiento { get; set; }
        public string nombreDoctor { get; set; }
        public string apellido { get; set; }
        public string cargo { get; set; }
        public Nullable<int> id_prescripcion { get; set; }
    
        public virtual TipoPrescripcion TipoPrescripcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valoracion_inicial> Valoracion_inicial { get; set; }
    }
}
