//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaUrgencia_v2._0.DataL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPrescripcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoPrescripcion()
        {
            this.Prescripcion_Emergencia = new HashSet<Prescripcion_Emergencia>();
        }
    
        public int id_tipo_prescripcion { get; set; }
        public Nullable<bool> via_oral { get; set; }
        public Nullable<bool> via_sublingual { get; set; }
        public Nullable<bool> via_transdermica { get; set; }
        public Nullable<bool> via_topica { get; set; }
        public Nullable<bool> via_otica { get; set; }
        public Nullable<bool> via_vaginal { get; set; }
        public Nullable<bool> via_oftalmica { get; set; }
        public Nullable<bool> via_inhalatoria { get; set; }
        public Nullable<bool> via_recta { get; set; }
        public Nullable<bool> via_intranasal { get; set; }
        public Nullable<bool> via_parenteral { get; set; }
        public string Prescripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescripcion_Emergencia> Prescripcion_Emergencia { get; set; }
    }
}
